# Generated by Django 4.2.4 on 2023-10-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_size_alter_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
